try {
    if (fibonacci(0) !== 0) {
        console.log('функция возвращает не то значение для 0');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 0');
}
try {
    if (fibonacci(1) !== 0) {
        console.log('функция возвращает не то значение для 1');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 1');
}
try {
    if (fibonacci(2) !== 1) {
        console.log('функция возвращает не то значение для 2');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 2');
}
try {
    if (fibonacci(3) !== 1) {
        console.log('функция возвращает не то значение для 3');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 3');
}
try {
    if (fibonacci(4) !== 2) {
        console.log('функция возвращает не то значение для 4');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 4');
}
try {
    if (fibonacci(5) !== 3) {
        console.log('функция возвращает не то значение для 5');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 5');
}
try {
    if (fibonacci(6) !== 5) {
        console.log('функция возвращает не то значение для 6');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 6');
}