try {
    if (countZeros(20) !== 2) {
        console.log('функция возвращает не то значение для 20');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 20');
}
try {
    if (countZeros(100) !== 11) {
        console.log('функция возвращает не то значение для 100');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 100');
}
try {
    if (countZeros(0) !== 0) {
        console.log('функция возвращает не то значение для 0');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 0');
}
try {
    if (countZeros(9) !== 0) {
        console.log('функция возвращает не то значение для 9');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 9');
}
try {
    if (countZeros(10) !== 1) {
        console.log('функция возвращает не то значение для 10');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 10');
}
try {
    if (countZeros(342) !== 64) {
        console.log('функция возвращает не то значение для 342');
    }
} catch (excep) {
    console.log('функция вызывает ошибку для 342');
}